# PRIMERA COLA (list)
cola = []
cola.append("A")
cola.append("B")
cola.append("C")
print("La cola es:", cola)
elemento = cola.pop(0)  
print("La cola después:", cola)

# SEGUNDA COLA (list)
cola = []
cola.append("M")
cola.append("R")
cola.append(1)
cola.append(6)
cola.append(9)
print("La cola es:", cola)  
elemento = cola.pop(3)
print("La cola después:", cola)

# TERCERA COLA (deque)
from collections import deque
cola = deque()
cola.append(265)
cola.append("tics")
cola.append(45)
cola.append("ias")
cola.append(12)
cola.append("admon")
print("La cola es:", list(cola))
elemento = cola.popleft()
print("La cola después de popleft:", list(cola))

# CUARTA COLA (deque)
from collections import deque
cola = deque()
cola.append(60)
cola.append("Rojo")
cola.append(75)
cola.append("Mañana")
cola.append(92)
cola.append("Pan")
cola.append(34)
cola.append("Rosa")
cola.append(21)
cola.append("Personas")
print("La cola es:", list(cola))
elemento = cola.popleft()  
print("El dato eliminado es:", elemento)
print("La cola después de popleft:", list(cola))

# QUINTA COLA (Queue)
from queue import Queue
cola = Queue()
cola.put("A")
cola.put("B")
cola.put("C")
print("La cola tiene", cola.qsize(), "elementos")  # Mostrar mensaje más claro
elemento = cola.get()
print("Elemento eliminado:", elemento)  # Corregí "elemento eliminado"
print("La cola después tiene:", cola.qsize(), "elementos")

# SEXTA COLA (Queue)
from queue import Queue
cola = Queue()
cola.put(43)
cola.put("Casa")
cola.put("Patio")
cola.put(86)
cola.put(43)
cola.put(86)
cola.put(43)
cola.put(86)
cola.put("Mesa")
cola.put("Casa")
print("La cola tiene", cola.qsize(), "elementos")
elemento = cola.get()
print("Elemento eliminado:", elemento)
print("La cola después tiene:", cola.qsize(), "elementos")


pila = []  
pila.append("A")
pila.append("A")
pila.append("B")
pila.append("C")
pila.append(23)
print("La pila es:", pila)
elemento = pila.pop()
print("Elemento eliminado:", elemento)  
print("La pila después de pop:", pila) 