cola=[]
elem1=int(input("ingresa un valor:"))
cola.append(elem1)
elem2=int(input("ingresa un valor:"))
cola.append(elem2)
elem3=int(input("ingresa un valor:"))
cola.append(elem3)
elem4=int(input("ingresa un valor:"))
cola.append(elem1)
elem5=int(input("ingresa un valor:"))
cola.append(elem1)
elem6=int(input("ingresa un valor:"))
cola.append(elem2)
elem7=int(input("ingresa un valor:"))
cola.append(elem3)
elem8=int(input("ingresa un valor:"))
cola.append(elem1)
print(cola)

